services:
  web-server:
    build: ./nginx
    ports:
      - "8081:80"

  multiplayer-server:
    build: ./server
    environment:
      - CORE_SENDING_ADDRESS=ws://core:40010
      - CORE_RECEIVING_ADDRESS=ws://core:42000

  core:
    build: ./core

  joypad:
    build: ./joypad

  viewer:
    build: ./server/static/viewer
